config/routes.rb
Rails.application.routes.draw do
  resources :personal_checklists, only: %i[index edit update]

  namespace :admin do
    namespace :forms do
      get 'publish/publisheding'
    end
    root to: 'forms#index'
    resources :forms
  end

  resources :checklists, except: %i[edit update]
  devise_for :users
  root to: 'checklists#index'
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id           :bigint           not null, primary key
#  comment      :text
#  significance :integer
#  question_id  :bigint
#  checklist_id :bigint
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Answer < ApplicationRecord
  belongs_to :checklist
  belongs_to :question
  validates :comment, presence: true, length: { minimum: 12 },
                      unless: proc { |a| a.significance == 'nothing' }
  enum significance: { nothing: 0, yes: 1, no: 2, na: 3 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checklist.rb
# == Schema Information
#
# Table name: checklists
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :text
#  project_uid :string
#  date        :datetime
#  form_id     :bigint
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#

class Checklist < ApplicationRecord
  belongs_to :user
  belongs_to :form
  has_many :answers, dependent: :destroy
  validates_presence_of :title
  accepts_nested_attributes_for :answers, reject_if:
  :all_blank, allow_destroy: true
  scope :published, -> { where(status: 'published') }
end

app/models/form.rb
# == Schema Information
#
# Table name: forms
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :text
#  status      :integer
#  date        :datetime
#  user_id     :bigint
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Form < ApplicationRecord
  belongs_to :user, optional: true
  has_many :checklists, dependent: :destroy
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, reject_if:
  :all_blank, allow_destroy: true
  enum status: { draft: 0, published: 1 }
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :text
#  form_id     :bigint
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Question < ApplicationRecord
  belongs_to :form
  has_many :answers, dependent: :destroy
  validates :title,  presence: true, length: { minimum: 4 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  admin                  :boolean          default(FALSE)
#

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :forms
  has_many :checklists
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info
  layout 'admin/layouts/admin'

  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  after_action :verify_authorized

  private

  def user_not_authorized
    flash[:alert] = t('pundit_permition')
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/admin/forms/publish_controller.rb
class Admin::Forms::PublishController < Admin::ApplicationController
  before_action :authenticate_user!
  before_action :authorize_policy

  def publisheding
    @form = Form.find(params[:id])
    @form.update_attributes(status: 'published')
    redirect_to admin_forms_path, success: t('form_status_p')
  end

  private

  def authorize_policy
    authorize Form
  end
end

app/controllers/admin/forms/unpublish_controller.rb
class Admin::Forms::UnpublishController < Admin::ApplicationController
  before_action :authenticate_user!
  before_action :authorize_policy


  private

  def authorize_policy
    authorize Form
  end
end

app/controllers/admin/forms_controller.rb
class Admin::FormsController < Admin::ApplicationController
  before_action :set_form, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :authorize_policy

  def new
    @form = Form.new
    @form.questions.build
  end

  def index
    @forms = Form.all.order(created_at: :desc)
  end

  def show; end

  def create
    @form = Form.new(form_params)
    if @form.save
      redirect_to admin_forms_path, success: t('form_create')
    else
      render 'new', danger: 'Form not updated'
    end
  end

  def edit; end

  def update
    if @form.update(form_params)
      redirect_to admin_form_path(@form.id), success: t('form_update')
    else
      render 'edit', danger: 'Form not updated'
    end
  end

  def destroy
    @form.destroy
    redirect_to admin_forms_path, danger: t('form_delete')
  end
  private

  def authorize_policy
    authorize Form
  end

  def form_params
    params.require(:form).permit(:title, :description, :project, :status, :date, questions_attributes: %i[id title description _destroy])
  end

  def set_form
    @form = Form.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info, :error

  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = t('pundit_permition')
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_policy

  def index
    @forms = Form.all.order(created_at: :desc)
    @checklists = Checklist.published
  end

  def show
    @form = Form.find(params[:id])
  end

  def new
    @form = Form.find(params[:id])
    @checklist = Checklist.new
    @checklist.answers.build
  end

  def create
    @checklist = Checklist.new(checklist_params)
    if @checklist.save
      redirect_to checklists_path, success: t('checklist_create')
    else
      redirect_to new_checklist_path(id: @checklist.form_id), danger:
      @checklist.errors.full_messages.join('. ')
    end
  end

  def destroy
    @checklist = Checklist.find(params[:id])
    @checklist.destroy
    redirect_to personal_checklists_path, danger: t('checklist_delete')
  end

  private

  def authorize_policy
    authorize Checklist
  end

  def checklist_params
    params.require(:checklist).permit(:title, :description, :project_uid, :form_id, :user_id, :date, answers_attributes: %i[id significance comment question_id])
  end
end

app/controllers/personal_checklists_controller.rb
class PersonalChecklistsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_policy

  def index
    current_user.checklists
  end

  def edit
    @checklist = Checklist.find(params[:id])
    @form = @checklist.form
    @checklist.answers
  end

  def update
    @checklist = Checklist.find(params[:id])
    if @checklist.update(checklist_params)
      redirect_to personal_checklists_path, success: t('checklist_update')

    else
      redirect_to  edit_personal_checklist_path(@checklist.id), danger:
      @checklist.errors.full_messages.join('. ')
    end
  end

  private

  def authorize_policy
    authorize Checklist
  end

  def checklist_params
    params.require(:checklist).permit(answers_attributes:
    %i[id significance comment question_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/personal_checklists_helper.rb
module PersonalChecklistsHelper
end

app/views/admin/checklists/_checklist_form.html.slim
= simple_form_for [:admin, @checklist] do |f|
  .form-inputs
    = f.input :title, label: 'Checklist title', required: true , error: 'Title is mandatory, please specify one'
    = f.input :description, label: 'Checklist detailed description'
    = f.input :status, :as => :select, :collection => Checklist.statuses.keys, selected: 1
  h3.d-flex.justify-content-center Questions
  table.table
    thead
      tr
        th
        th Question title
        th Question datailed description
    tbody.quest
     = f.simple_fields_for :questions do |question|
       = render 'question_fields', f: question
    .form-actions
      = link_to 'back', admin_checklists_path,                                            \
      data: { confirm: 'Unsaved changes will be deleted. Are you sure?' } ,  class: 'btn btn-secondary ml-3 mb-3 '
      = f.submit 'Save',  class: 'btn btn-success ml-3 mb-3'
      = link_to_add_association 'add question', f, :questions, class: 'btn btn-primary ml-3 mb-3', data: { association_insertion_node: '.quest', association_insertion_method: :append }

app/views/admin/checklists/show.html.slim
.conatiner.mt-5
  .col-lg-12
    .row.justify-content-center
      .conatiner
          p
            h2.strong Checklist Title:
            ins = @checklist.title
          p
            h4.strong Checklist Text:
            ins = @checklist.description
            - @checklist.questions.each do |question|
              p
                h4.strong Question title:
                ins = question.title
              p
                h6.strong Question Description:
                ins = question.description
          = link_to 'Edit', edit_admin_checklist_path
          br
          = link_to 'Back', admin_checklists_path

app/views/admin/forms/_form_form.html.slim
= simple_form_for [:admin, @form] do |f|
  .form-inputs
    = f.input :title, label: 'Form title', required: true , error: 'Title is mandatory, please specify one'
    = f.input :description, label: 'Form detailed description'
    = f.input :status, :as => :select, :collection => Form.statuses.keys, selected: 1
  h3.d-flex.justify-content-center Questions
  table.table
    thead
      tr
        th
        th Question title
        th Question datailed description
    tbody.quest
     = f.simple_fields_for :questions do |question|
       = render 'question_fields', f: question
    .form-actions
      = link_to 'back', admin_forms_path,                                            \
      data: { confirm: 'Unsaved changes will be deleted. Are you sure?' } ,  class: 'btn btn-secondary ml-3 mb-3 '
      = f.submit 'Save',  class: 'btn btn-success ml-3 mb-3'
      = link_to_add_association 'add question', f, :questions, class: 'btn btn-primary ml-3 mb-3', data: { association_insertion_node: '.quest', association_insertion_method: :append }

app/views/admin/forms/_question_fields.html.slim
tr.nested-fields
  td
    = link_to_remove_association "remove question", f, data: { confirm: 'Are you sure, that you want to delete the question?' }, class: 'btn btn-danger btn-xs'
  td= f.input :title, label: false, required: true
  td= f.input :description, label: false

app/views/admin/forms/edit.html.slim
.container.mt-4
  h1.h1.d-flex.justify-content-center Edit Form
  = render 'form_form'

app/views/admin/forms/index.html.slim
.conatiner.mt-4
  .col-lg-12.d-flex.justify-content-center
    .row
      .col-lg-12
        = link_to 'Add Checklist', new_admin_form_path, class: 'btn btn-secondary ml-2 mb-4'
        table.table-bordered
          thead
            tr
              th[scope="col"]
                | Name
              th[scope="col"]
                | Description
              th[scope="col"]
                | Status
              th[scope="col"]
                | Published
              th[scope="col"]
                | Actions
          tbody
            - @forms.each.with_index(1) do |form, i|
              tr
                td = form.title
                td = form.description
                td = form.status
                td = Date.today.to_s.to_date
                td width="320px"
                  - if form.status == 'draft'
                    = link_to 'publish', admin_forms_publish_publisheding_path(id: form.id), class: 'btn btn-info  mr-1'
                  = link_to 'edit', edit_admin_form_path(form.id),      class: 'btn btn-secondary mr-1 '
                  = link_to 'show', admin_form_path(form.id),      class: 'btn btn-secondary mr-1 '
                  = link_to 'delete', admin_form_path(form.id), method: :delete,                                            \
                  data: { confirm: 'Are you sure?' } ,  class: 'btn btn-danger mr-1 '

app/views/admin/forms/new.html.slim
.container.mt-4
  h1.h1.d-flex.justify-content-center Create New Form
  = render 'form_form'

app/views/admin/forms/show.html.slim
.conatiner.mt-5
  .col-lg-12
    .row.justify-content-center
      .conatiner
          p
            h2.strong.d-flex.justify-content-center Checklist Title:
            h4.ins.d-flex.justify-content-center = @form.title
          p
            h4.strong Checklist Text:
            h5.ins = @form.description
            - @form.questions.each do |question|
              p
                h4.strong Question title:
                h6.ins = question.title
              p
                h4.strong Question Description:
                h6.ins = question.description
          = link_to 'Edit', edit_admin_form_path
          br
          = link_to 'Back', admin_forms_path

app/views/admin/layouts/_flash_messages.html.slim
- flash.each do |name, message|
  div class=("alert alert-#{name}")
    button.close data-dismiss="alert" type="button"   ×
    = message

app/views/admin/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.us
  a.navbar-brand.logo href="#{admin_root_url}" Checklists
  button.navbar-toggler aria-controls="navbarNavDropdown" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNavDropdown" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  ul.nav.navbar-nav.navigation.d-flex.justify-content-left
    - if user_signed_in?
      li.nav-item
       li = link_to('Field Checklists', root_path)
       li = link_to('Configure Checklists',  personal_checklists_path)
       li = link_to('Admin', admin_root_path) if current_user.admin == true
       li = link_to('Logout', destroy_user_session_path, method: :delete)
       li = link_to current_user.email, edit_user_registration_path
    - else
      li.nav-item
       li = link_to('Login', new_user_session_path)
       li = link_to 'Sign up', new_user_registration_path

app/views/admin/layouts/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Testove
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render partial: 'admin/layouts/navbar'
    .row
      .col-md-12
        = render partial: 'admin/layouts/flash_messages'
        = yield

app/views/checklists/_modal_view.html.slim
button.btn.btn-secondary.ml-2.mb-4 data-target="#exampleModalCenter" data-toggle="modal" type="button"
  | Fill Checklist
#exampleModalCenter.modal.fade aria-hidden="true" aria-labelledby="exampleModalCenterTitle" role="dialog" tabindex="-1"
  .modal-dialog.modal-lg.modal-dialog-centered role="document"
    .modal-content
      .modal-header
        h5#exampleModalLongTitle.modal-title Modal Window
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  ×
      .modal-body.d-flex.justify-content-center
        .dropdown.show
          a#dropdownMenuLink.btn.btn-secondary.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            | Select Checklist
          ul.dropdown-menu aria-labelledby="dropdownMenuLink"
            - @forms.each do |form|
              li.dropdown-item
                = link_to form.title, new_checklist_path(id: form.id), class: 'a-link'
      .modal-footer
        button.btn.btn-secondary data-dismiss="modal" type="button"  Cancel

app/views/checklists/edit.html.slim
.col-lg-12.mt-5.ml-5
  .row.justify-content-center
    .conatiner
      h1.d-flex.justify-content-center Edit Checklist
      h3.d-flex.justify-content-center = @checklist.title
      br
      h5.d-flex.justify-content-center = @checklist.description
      br
        = simple_form_for @checklist, method: :patch do |f|
          - @form.questions.each do |question|
            = f.simple_fields_for :answers do |p|
              = p.hidden_field :question_id, value: question.id
              .d-flex.justify-content-center = p question.title
              = p.input :significance, :as => :select, :collection => Answer.significances.keys, label: question.description
              = p.input :comment, required: true, error: 'comment is mandatory, must be at least 12 characters'
          = link_to 'back', checklists_path, data: { confirm: 'Unsaved changes will be deleted. Are you sure?' } ,  class: 'btn btn-secondary  mb-3 '
          = f.submit 'Save',  class: 'btn btn-success ml-3 mb-3'

app/views/checklists/index.html.slim
.conatiner.mt-5
  .col-lg-12.d-flex.justify-content-center
    .row
      .col-lg-12
        = render 'modal_view'
        table.table-bordered
          thead
            tr
              th[scope="col"]
                | Project
              th[scope="col"]
                | Checklist
              th[scope="col"]
                | Updated
              th[scope="col"]
                | Questions
              -if current_user.admin == true
                th[scope="col"]
                  | Actions
          tbody
            - @forms.each.with_index(1) do |form, i|
              tr
                td  PRG1
                td = form.title
                td = Date.today.to_s.to_date
                td.chartik = bar_chart  Answer.group(:significance).count, height: "100px"
                -if current_user.admin == true
                  td
                    ul.navbar-nav.mr-auto
                      li.nav-item
                        a.nav-link  = link_to 'Show', checklist_path(form.id), class: 'btn btn-secondary'

app/views/checklists/my_checklist.html.slim
.conatiner.mt-5
  .col-lg-12.d-flex.justify-content-center
    .row
      .col-lg-12
        table.table-bordered
          thead
            tr
              th[scope="col"]
                | My Checklists
              th[scope="col"]
                | Updated
              th[scope="col"]
                | Questions
              th[scope="col"]
                | Actions
          tbody
            - current_user.checklists.each.with_index(1) do |checklist, i|
              tr
                td = checklist.title
                td = Date.today.to_s.to_date
                td.chartik = bar_chart  Answer.group(:significance).count, height: "100px"
                td
                  ul.navbar-nav.mr-auto
                    li.nav-item
                      a.nav-link  = link_to 'Edit', edit_checklist_path(checklist.id), class: 'btn btn-success'
                    li.nav-item
                      a.nav-link  = link_to 'delete', checklist_path(checklist.id), method: :delete,                                            \
                    data: { confirm: 'Are you sure?' } ,  class: 'btn btn-danger'

app/views/checklists/new.html.slim
.col-lg-12.mt-5.ml-5
  .row.justify-content-center
    .conatiner
      h3.d-flex.justify-content-center = @form.title
      br
      h5.d-flex.justify-content-center = @form.description
      br
        = render 'layouts/error_messages', form_object: @checklist
        = simple_form_for @checklist, method: :post, url: checklists_path do |f|
          = f.hidden_field :title,       value: @form.title
          = f.hidden_field :description, value: @form.description
          = f.hidden_field :form_id,     value: @form.id
          = f.hidden_field :user_id,     value: current_user.id
          - @form.questions.each do |question|
            = f.simple_fields_for :answers do |p|
              = p.hidden_field :question_id, value: question.id
              .d-flex.justify-content-center = p question.title
              = p.input :significance, :as => :select, :collection => Answer.significances.keys, selected: 0, label: question.description
              = p.input :comment, required: true, error: 'comment is mandatory, must be at least 12 characters'
          = link_to 'back', checklists_path, data: { confirm: 'Unsaved changes will be deleted. Are you sure?' } ,  class: 'btn btn-secondary  mb-3 '
          = f.submit 'Save',  class: 'btn btn-success ml-3 mb-3'

app/views/checklists/show.html.slim
.col-lg-12.mt-5.ml-5
  .row.justify-content-center
    .conatiner
      h1.d-flex.justify-content-center Checklist
      br
      br
      .d-flex.justify-content-center.form-tit = @form.title
      .d-flex.justify-content-center.form-desc = @form.description
      br
      br
      br
      h2.d-flex.justify-content-center Question:
      - @form.questions.each do |question|
          br
          h3.d-flex.justify-content-center.form-quest = p question.title
          h5.d-flex.justify-content-center.form-quest = p question.description
          br
          - if question.answers.first.present?
            h5.d-flex.justify-content-center.form-quest = p  question.answers.first.significance
            h5.d-flex.justify-content-center.form-quest = p  question.answers.first.comment
      = link_to 'back', checklists_path, class: 'btn btn-secondary'

app/views/layouts/_error_messages.html.slim
- if form_object.errors.any?
  #error_explanation
    .alert.alert-danger
      | The form contains #{pluralize(form_object.errors.count, "error")}.
    ul
      - form_object.errors.full_messages.each do |msg|
        li= msg

app/views/layouts/_flash_messages.html.slim
- flash.each do |name, message|
  div class=("alert alert-#{name}")
    button.close data-dismiss="alert" type="button"  ×
    = message

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.us
  a.navbar-brand.logo href="/" Checklists
  button.navbar-toggler aria-controls="navbarNavDropdown" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNavDropdown" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  ul.nav.navbar-nav.navigation.d-flex.justify-content-left
    - if user_signed_in?
      li.nav-item
       li = link_to('Field Checklists', root_path)
       li = link_to('Configure Checklists',  personal_checklists_path)
       li = link_to('Admin', admin_root_path) if current_user.admin == true
       li = link_to('Logout', destroy_user_session_path, method: :delete)
       li = link_to current_user.email, edit_user_registration_path
    - else
      li.nav-item
       li = link_to('Login', new_user_session_path)
       li = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Testove
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render partial: 'layouts/navbar'
    .row
      .col-md-12
        = render partial: 'layouts/flash_messages'
        = yield

app/views/personal_checklists/edit.html.slim
.col-lg-12.mt-5.ml-5
  .row.justify-content-center
    .conatiner
      h1.d-flex.justify-content-center Edit Checklist
      h3.d-flex.justify-content-center = @checklist.title
      br
      h5.d-flex.justify-content-center = @checklist.description
      br
        = render 'layouts/error_messages', form_object: @checklist
        = simple_form_for @checklist, method: :patch, url: personal_checklist_path do |f|
          - @form.questions.each do |question|
            = f.simple_fields_for :answers, question.answers.first do |p|
              = p.hidden_field :question_id, value: question.id
              .d-flex.justify-content-center = p question.title
              = p.input :significance, :as => :select, :collection => Answer.significances.keys, label: question.description
              = p.input :comment, required: true, error: 'comment is mandatory, must be at least 12 characters'
          = link_to 'back', checklists_path, data: { confirm: 'Unsaved changes will be deleted. Are you sure?' } ,  class: 'btn btn-secondary  mb-3 '
          = f.submit 'Save',  class: 'btn btn-success ml-3 mb-3'

app/views/personal_checklists/index.html.slim
.conatiner.mt-5
  .col-lg-12.d-flex.justify-content-center
    .row
      .col-lg-12
        table.table-bordered
          thead
            tr
              th[scope="col"]
                | My Checklists
              th[scope="col"]
                | Updated
              th[scope="col"]
                | Questions
              th[scope="col"]
                | Actions
          tbody
            - current_user.checklists.each.with_index(1) do |checklist, i|
              tr
                td = checklist.title
                td = Date.today.to_s.to_date
                td.chartik = bar_chart  Answer.group(:significance).count, height: "100px"
                td
                  ul.navbar-nav.mr-auto
                    li.m-1
                      = link_to 'Edit', edit_personal_checklist_path(checklist.id), class: 'btn btn-success'
                    li.m-1
                      = link_to 'delete', checklist_path(checklist.id), method: :delete,                                            \
                    data: { confirm: 'Are you sure?' } ,  class: 'btn btn-danger'